language: node_js

node_js:
  - "10"

install:
  - npm install

script:
  - npm run test
  - ./node_modules/coveralls/bin/coveralls.js < ./coverage/lcov.info;

cache:
  directories:
    - node_modules
